<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    // 把回调地狱变成链式调用
    // 这里的延迟1000ms用来模拟请求数据时的时间延迟
    new Promise((resolve, reject)=>{
      // 请求
      setTimeout(() => {
        // 成功时调用resolve
        // resolve()
        // 请求失败时调用reject   后续用.catch调用
        reject('请求失败')
      }, 1000);
    }).then(()=>{
        // 处理
        console.log(666);
        console.log(666);
        console.log(666);
        console.log(666);
        console.log(666);
        console.log(666);
        console.log(666);

        return new Promise((resolve, reject)=>{
          setTimeout(() => {
            resolve()
            reject('请求失败2')
          }, 1000);
        })
    }, err =>{
      console.log(err);
    })
    // .catch((err)=>{
    //   console.log(err);
    // })
    .then(()=>{
      console.log(777);
      console.log(777);
      console.log(777);
      console.log(777);
      console.log(777);
      console.log(777);
      console.log(777);

      return new Promise((resolve, reject)=>{
          setTimeout(() => {
            resolve()
            reject('请求失败3')
          }, 1000);
        })
    })
    // .catch((err)=>{
    //   console.log(err);
    // })
    .then(()=>{
      console.log(888);
      console.log(888);
      console.log(888);
      console.log(888);
      console.log(888);
      console.log(888);
      console.log(888);
    })
    // .catch((err)=>{
    //   console.log(err);
    // })
    // .catch((err)=>{
    //   console.log(err);
    // })
    // .catch((err)=>{
    //   console.log(err);
    // })
    console.log('qweqwe');
  </script>
</body>
</html>